### ISSUE TITLE
how to align changelogs (if possible at all) between SLE and openSUSE

### ISSUE THREAD

**Issue by wrosenauer** [openSUSE/firefox-maintenance#14]

**Comment by wrosenauer** [comment]
I'm not sure if this can be achieved consistently at all.
openSUSE:Factory is probably the only common denominator where all packages inherit their changelog once branched for new Leap/SLE versions.
Within the lifetime of a Leap/SLE version those will deviate.

The question is more: is there any sync possible within such a cycle and I'm not sure about it.

**Comment by msirringhaus** [comment]
We could even think about not putting changelogs in the repo at all.

**Comment by wrosenauer** [comment]
Probably a very good point for this repo here. If we assume the above that changelogs will differ and always (at some point) come back to the Factory version we have probably done what is possible and makes sense.

**Comment by msirringhaus** [comment]
Question is: If we drop the changelog completely from this repo, is there any need to sync up with Factory at all? 

We could just let the changelogs be OBS-only. If the changelogs are produced by the script in firefox-scripts, they should usually only differ in author and date anyways.

**Comment by msirringhaus** [comment]
I removed all changes-files from the repo with 574a25c.
They are also not synced anymore by `sync_ff`.
