### ISSUE TITLE
Remove source-stamp.txt

### ISSUE THREAD

**Issue by msirringhaus** [openSUSE/firefox-maintenance#16]
Given that we now have `tar_stamps`, we could probably get rid of `source-stamp.txt`, unless there is some reason to keep it.

**Comment by wrosenauer** [comment]
source-stamp.txt is currently sourced from the build process:
source %{SOURCE5}
...
export MOZ_SOURCE_CHANGESET=$REV
export SOURCE_REPO=$REPO
export source_repo=$REPO
export MOZ_SOURCE_REPO=$REPO

So yes, it can be replaced if the values are correctly referenced here as well.

**Comment by wrosenauer** [comment]
The information here is (at least) used in about:buildconfig

**Comment by msirringhaus** [comment]
Ah thanks for that background-info.

Starting with Firefox 69, the tarballs published by Mozilla now contain a `sourcestamp.txt`-file with this information directly. 
Due to a bug in their build-system this file is unfortunately empty in 68 esr. 

We might be able to switch to the built-in file once it is available everywhere, which I think would be less error-prone anyways than filling it out by hand.

**Comment by cgrobertson** [comment]
With SLE-15 FF68esr spec file now in sync with openSUSE we need to decide how we are going to keep the SLE-11/12 spec files in sync. The main issue is the addition of "firefox-" dependencies for packages required but not found on the lesser platforms.

Right now for SLE-12 we have to package the newer versions of the following:
```
nasm >= 2.13 (currently use: firefox-nasm == 2.13)
nodejs8 >= 8.11
python2-xml
python3 >= 3.5 (currently use: firefox-python3 == 3.6)
xvfb-run
```
On SLE-11 we we maintain over 30 different newer versions of dependent packages for Firefox (I won't list them). So the question is how closely do we want to keep these lesser SLE version FF spec files in sync? For instance, do we want to wrap all "Buildrequires" with an "if suse_version..." like this:
```
%if 0%{?suse_version} < 1500
BuildRequires:  firefox-nasm
%else
BuildRequires:  nasm >= 2.13
%endif
```
Or just this:
`BuildRequires:  firefox-nasm`

The former has the tendency to make the spec file messy.

Please, I would like to get your feedback on this.
