### ISSUE TITLE
Deactivate DoH?

### ISSUE THREAD

**Issue by msirringhaus** [openSUSE/firefox-maintenance#18]
DNS over HTTPS has now been activated for US-users in normal releases. It is not yet active for ESR.

Since this feature bypasses the system-settings for DNS, it is a highly controversial feature, esp. for Linux users (apart from the fact that it funnels all DNS resolution to cloudflare). 

Fedora and RedHat have already confirmed to deactivate it by default: 
https://bugzilla.redhat.com/show_bug.cgi?id=1751410

I think, esp. for ESR this would be a good idea, as companies often use special DNS-setups and wouldn't want the browser to just bypass that.

**Comment by wrosenauer** [comment]
For regular releases and therefore Tumbleweed I want and I will disable DOH by default. This MUST be an opt-in feature even for US people in my opinion.
The only technical decision I have not taken yet is if it should be disabled in the Firefox package or the according branding package.

**Comment by msirringhaus** [comment]
Just to repeat what I already wrote in the chatroom:

In my opinion, it could go into the core package, as this is something that affects the underlying OS, which I consider somewhat broken if not all applications adhere to the DNS-settings of it.
