### ISSUE TITLE
new branding-openSUSE package release

### ISSUE THREAD

**Issue by wrosenauer** [openSUSE/firefox-maintenance#22]
For openSUSE I created a new branding package because of the following changes:
- moved prefs to the core Firefox package (also cherry-picked with 0d48d350c1bbb1fc3e36e2e72e40ef6197a51ff4
- made it a multibuild package to provide two flavors (MozillaFirefox and firefox-esr)

So I bumped the version to 68 and increased the requirement here:
d4982decaa827304ee4c242e7891e161d5386804
along with removal of unlogic use of branding definition.

Please assess if and what exactly you would like to do for the SUSE branding packaging.

**Comment by msirringhaus** [comment]
I adapted the branding package for the move of the extension settings to the core package. 

I have not yet cherry-picked the multibuild-commit. Need to discuss, if we are going to do this or not for SLE.

**Comment by msirringhaus** [comment]
Cherry-picked d4982de as well

**Comment by msirringhaus** [comment]
I think this can be closed for now.
