### ISSUE TITLE
Update locales build

### ISSUE THREAD

**Issue by msirringhaus** [openSUSE/firefox-maintenance#23]
The current way of building locales seems to be deprecated (https://bugzilla.mozilla.org/show_bug.cgi?id=1580701) 

There is, however, a build-target `./mach build langpack-$language` to do this, which would vastly simplify the current way. 

Also: Currently languages are build in the `%install`-section which I find a bit weird, as IMHO it should be part of `%build`.

**Comment by wrosenauer** [comment]
This has been fixed today for relevant branches. (Both issues)
