### ISSUE TITLE
MozillaFirefox 91 ESR stopped working on banking site

### ISSUE THREAD

**Issue by kenyapcomau** [openSUSE/firefox-maintenance#36]
System is openSUSE Leap 15.3 on x86_64 which uses SUSE Linux Enterprise 15 packages.

Today, the newly updated MozillaFirefox 91 ESR package won't work on a banking site that previously did. Display keeps spinning its wheels and console shows:

Check for system-wide FIPS mode is required and /proc/sys/crypto/fips_enabled cannot be opened for reading - aborting
Redirecting call to abort() to mozalloc_abort

A search found this patch which is how I got here. I assume that this is the problem and that fixed packages will be released soon? Working around by using a different browser for now.

https://github.com/openSUSE/firefox-maintenance/blob/master/mozilla-sandbox-fips.patch

Edit: Just to add that I suspect this problem is impacting performance as it seems to slow down access to many other sites.

**Comment by msirringhaus** [comment]
So, NSS is trying to open `/proc/sys/crypto/fips_enabled`, but apparently fails to do so.
Could you try to do `cat /proc/sys/crypto/fips_enabled` in the commandline?

**Comment by msirringhaus** [comment]
Ok, so this is a weird one. 
I've just tested with upstream Firefox 93 and even Chromium. The login-page redirect does not work for **any** of them, for the page you have provided us with. So, I would think the page itself is broken.
Our own build still shows the FIPS-abort, which shouldn't happen (I could reproduce this locally). But I think it is not responsible for the behavior you see.
