### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by msirringhaus** [openSUSE/firefox-maintenance#4]
There are two questions concerning branding:

1. Do we want to merge the different branding-packages as well and move them here?

~2. I might have messed up my VM, but I think both branding packages are somewhat broken. Installing FF 60 on leap15 gives me a bookmark-directory `openSUSE` which is empty. (SUSE branding is broken in multiple places)~
Sorry, after removing all config-files and reinstalling FF, bookmarks where there!

**Comment by wrosenauer** [comment]
Not sure if we find enough agreement in the branding package. It sounds risky to me even if we align now that new requirements would require a split again?

**Comment by msirringhaus** [comment]
I don't think this makes sense at the moment. These are going to stay separate. We might however open github-issues to inform the other party of changes
