### ISSUE TITLE
Fix %check - section for NSS

### ISSUE THREAD

**Issue by msirringhaus** [openSUSE/firefox-maintenance#8]
NSS has test binaries, which should be run after compilation.
NSPR is already doing this in the %check - section.
We should do the same for NSS, in order to be sure the build was successful.

**Comment by wrosenauer** [comment]
# disabled temporarily bmo#1236340
%define run_testsuite 0

The test stuff is prepared (but currently disabled) in the %build section already.

**Comment by msirringhaus** [comment]
Ah, thanks. I was just quickly looking for a check-section and missed that.
And that upstream bug has only been open for 4 years now. Very promising

**Comment by msirringhaus** [comment]
%check-section works now.
